import type { OxlintConfig } from 'vite-plus/lint';

const PARENT_IMPORT = {
  group: ['../*', '..', '../**'],
  message:
    "Pas de chemin relatif qui remonte (../) : passer par l'alias @/ ou par le nom du paquet.",
};

export const oxlint: OxlintConfig = {
  plugins: ['typescript', 'unicorn', 'oxc', 'react', 'jsx-a11y', 'vitest'],
  categories: { correctness: 'off' },
  options: { typeAware: true, typeCheck: true },
  ignorePatterns: ['**/dist/**', '**/coverage/**', 'apps/api/drizzle/**'],
  rules: {
    'array-callback-return': 'error',
    'constructor-super': 'error',
    'default-case-last': 'warn',
    'dot-notation': 'warn',
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'for-direction': 'error',
    'getter-return': 'error',
    'jsx-a11y/alt-text': 'error',
    'jsx-a11y/anchor-ambiguous-text': 'error',
    'jsx-a11y/anchor-is-valid': 'error',
    'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
    'jsx-a11y/aria-props': 'error',
    'jsx-a11y/aria-proptypes': 'error',
    'jsx-a11y/aria-role': 'error',
    'jsx-a11y/aria-unsupported-elements': 'error',
    'jsx-a11y/autocomplete-valid': 'error',
    'jsx-a11y/click-events-have-key-events': 'error',
    'jsx-a11y/heading-has-content': 'error',
    'jsx-a11y/html-has-lang': 'error',
    'jsx-a11y/iframe-has-title': 'error',
    'jsx-a11y/img-redundant-alt': 'error',
    'jsx-a11y/interactive-supports-focus': 'error',
    'jsx-a11y/label-has-associated-control': 'error',
    'jsx-a11y/lang': 'error',
    'jsx-a11y/media-has-caption': 'error',
    'jsx-a11y/mouse-events-have-key-events': 'error',
    'jsx-a11y/no-access-key': 'error',
    'jsx-a11y/no-aria-hidden-on-focusable': 'error',
    'jsx-a11y/no-autofocus': 'error',
    'jsx-a11y/no-distracting-elements': 'error',
    'jsx-a11y/no-interactive-element-to-noninteractive-role': 'error',
    'jsx-a11y/no-noninteractive-element-to-interactive-role': 'error',
    'jsx-a11y/no-noninteractive-tabindex': 'error',
    'jsx-a11y/no-redundant-roles': 'error',
    'jsx-a11y/no-static-element-interactions': 'error',
    'jsx-a11y/role-has-required-aria-props': 'error',
    'jsx-a11y/role-supports-aria-props': 'error',
    'jsx-a11y/scope': 'error',
    'jsx-a11y/tabindex-no-positive': 'error',
    'no-array-constructor': 'warn',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
    'no-const-assign': 'error',
    'no-constant-condition': 'error',
    'no-constructor-return': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': ['warn', { allowEmptyCatch: true }],
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-eval': 'error',
    'no-ex-assign': 'warn',
    'no-extra-boolean-cast': 'warn',
    'no-extra-label': 'warn',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-inner-declarations': 'error',
    'no-irregular-whitespace': 'warn',
    'no-label-var': 'error',
    'no-lone-blocks': 'warn',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-proto': 'warn',
    'no-prototype-builtins': 'warn',
    'no-regex-spaces': 'warn',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'warn',
    'no-setter-return': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'warn',
    'no-this-before-super': 'error',
    'no-unneeded-ternary': 'warn',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-labels': 'warn',
    'no-unused-private-class-members': 'warn',
    'no-unused-vars': 'warn',
    'no-useless-backreference': 'warn',
    'no-useless-catch': 'warn',
    'no-useless-constructor': 'warn',
    'no-useless-escape': 'warn',
    'no-useless-rename': 'warn',
    'no-with': 'error',
    'oxc/bad-min-max-func': 'error',
    'oxc/misrefactored-assign-op': 'error',
    'oxc/no-accumulating-spread': 'warn',
    'prefer-arrow-callback': 'warn',
    'prefer-const': 'warn',
    'prefer-exponentiation-operator': 'warn',
    'prefer-numeric-literals': 'warn',
    'prefer-regex-literals': 'warn',
    'prefer-rest-params': 'warn',
    'prefer-template': 'warn',
    radix: 'warn',
    'react/exhaustive-deps': 'error',
    'react/jsx-key': 'error',
    'react/jsx-no-comment-textnodes': 'error',
    'react/jsx-no-duplicate-props': 'error',
    'react/jsx-no-script-url': 'error',
    'react/jsx-no-target-blank': 'error',
    'react/jsx-no-useless-fragment': ['warn', { allowExpressions: true }],
    'react/no-array-index-key': 'error',
    'react/no-children-prop': 'error',
    'react/no-danger': 'error',
    'react/no-danger-with-children': 'error',
    'react/no-render-return-value': 'error',
    'react/rules-of-hooks': 'error',
    'react/void-dom-elements-no-children': 'error',
    'require-yield': 'error',
    'typescript/adjacent-overload-signatures': 'warn',
    'typescript/ban-ts-comment': 'warn',
    'typescript/consistent-type-exports': 'warn',
    'typescript/consistent-type-imports': 'error',
    'typescript/no-duplicate-enum-values': 'warn',
    'typescript/no-empty-interface': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-extra-non-null-assertion': 'warn',
    'typescript/no-extraneous-class': 'warn',
    'typescript/no-invalid-void-type': 'warn',
    'typescript/no-misused-new': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-non-null-assertion': 'warn',
    'typescript/no-this-alias': 'warn',
    'typescript/no-unnecessary-type-constraint': 'warn',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-function-type': 'warn',
    'typescript/no-useless-empty-export': 'warn',
    'typescript/no-wrapper-object-types': 'warn',
    'typescript/prefer-function-type': 'warn',
    'typescript/prefer-literal-enum-member': 'warn',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/prefer-optional-chain': 'warn',
    'unicorn/no-document-cookie': 'warn',
    'unicorn/no-instanceof-array': 'warn',
    'unicorn/no-thenable': 'error',
    'unicorn/no-useless-switch-case': 'warn',
    'unicorn/prefer-array-flat-map': 'warn',
    'unicorn/prefer-array-index-of': 'warn',
    'unicorn/prefer-date-now': 'warn',
    'unicorn/prefer-node-protocol': 'warn',
    'unicorn/prefer-number-properties': 'warn',
    'use-isnan': 'error',
    'valid-typeof': 'error',
    'vitest/no-duplicate-hooks': 'error',
    'vitest/no-focused-tests': 'warn',
    'no-restricted-imports': ['error', { patterns: [PARENT_IMPORT] }],
  },
  overrides: [
    {
      files: [
        'apps/api/src/admin/audit.ts',
        'apps/api/src/admin/settings.ts',
        'apps/api/src/admin/store.ts',
        'apps/api/src/admin/users.ts',
        'apps/api/src/auth/admin-access.ts',
      ],
      rules: { 'typescript/no-explicit-any': 'off' },
    },
    {
      files: [
        'apps/web/src/admin/AdminShell.tsx',
        'apps/web/src/admin/EntityList.tsx',
        'apps/web/src/admin/FieldInput.tsx',
      ],
      rules: { 'react/exhaustive-deps': 'off' },
    },
    {
      files: ['apps/web/src/ui/Table.tsx'],
      rules: { 'jsx-a11y/no-noninteractive-tabindex': 'off' },
    },
  ],
};
